// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJtjB8D3yEdLJIy0Q12C1Ld6eegoQHUNA',
    appId: '1:140866276032:web:018eb53bdd5ab69593fb25',
    messagingSenderId: '140866276032',
    projectId: 'phoneauthflutter-77b6c',
    authDomain: 'phoneauthflutter-77b6c.firebaseapp.com',
    storageBucket: 'phoneauthflutter-77b6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoY_kO78l0Du_1Np1qLh1PxMhCOssBgj8',
    appId: '1:140866276032:android:365b601b1c6dc2db93fb25',
    messagingSenderId: '140866276032',
    projectId: 'phoneauthflutter-77b6c',
    storageBucket: 'phoneauthflutter-77b6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4afL39DcIXPbZbTGTqHIbRNQ2HQSWVCI',
    appId: '1:140866276032:ios:716b02b98a6a5cd293fb25',
    messagingSenderId: '140866276032',
    projectId: 'phoneauthflutter-77b6c',
    storageBucket: 'phoneauthflutter-77b6c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4afL39DcIXPbZbTGTqHIbRNQ2HQSWVCI',
    appId: '1:140866276032:ios:716b02b98a6a5cd293fb25',
    messagingSenderId: '140866276032',
    projectId: 'phoneauthflutter-77b6c',
    storageBucket: 'phoneauthflutter-77b6c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJtjB8D3yEdLJIy0Q12C1Ld6eegoQHUNA',
    appId: '1:140866276032:web:7c928e767f16d76e93fb25',
    messagingSenderId: '140866276032',
    projectId: 'phoneauthflutter-77b6c',
    authDomain: 'phoneauthflutter-77b6c.firebaseapp.com',
    storageBucket: 'phoneauthflutter-77b6c.appspot.com',
  );
}
